import { randomUUID } from 'node:crypto';
import assert from 'node:assert/strict';
import { prisma } from '../lib/prisma';
import { alignment, createDraft, editDraft, saveEvidence, tailor, updateEvidence, savePreferences, createStory, chargeRecommendations } from '../modules/career/career.service';
import { listApplications, updateApplication } from '../modules/application/application.service';
import { closeRedis } from '../lib/redis';

// Explicit opt-in: uses isolated synthetic users, then deletes only those users.
if (process.env.RUN_CAREER_DB_TEST !== 'true') throw new Error('Set RUN_CAREER_DB_TEST=true to run the isolated database test.');
const users = [`career-test-${randomUUID()}`, `career-test-${randomUUID()}`];
try {
  for (const id of users) await prisma.user.create({ data: { id, name: 'Career integration test', email: `${id}@example.invalid` } });
  const userId = users[0]!; const otherId = users[1]!;
  const template = await prisma.resumeTemplate.findFirst({ select: { id: true } });
  if (!template) throw new Error('A resume template is required for this test.');
  const resume = await prisma.resume.create({ data: { userId, templateId: template.id, title: 'Synthetic test resume', contentData: { summary: 'Built React dashboards.' } } });
  const job = await prisma.job.create({ data: { userId, company: 'Synthetic company', title: 'Engineer', description: 'Required experience building React dashboards.', lifecycle: 'UNKNOWN' } });
  const evidence = await saveEvidence(userId, { title: 'Dashboard', statement: 'Built React dashboards.', source: 'Synthetic fixture', status: 'USER_CONFIRMED', technologies: ['React'], details: {} });
  await assert.rejects(() => alignment(otherId, job.id, resume.id), /not found/);
  const first = await alignment(userId, job.id, resume.id);
  const second = await alignment(userId, job.id, resume.id);
  assert.equal(first.id, second.id);
  const usage = await prisma.careerUsage.findFirst({ where: { userId, feature: 'alignment' } });
  assert.equal(usage?.used, 1);
  const input = { jobId: job.id, resumeId: resume.id, evidenceIds: [evidence.id], kind: 'APPLICATION' as const, tone: 'neutral' as const, length: 'standard' as const };
  await assert.rejects(() => createDraft(otherId, input), /not found/);
  const draft = await createDraft(userId, input);
  await assert.rejects(() => editDraft(otherId, draft.id, { subject: 'Test', body: 'Edited', reviewed: true }), /not found/);
  const edited = await editDraft(userId, draft.id, { subject: 'Reviewed', body: draft.body, reviewed: true });
  assert.ok(edited.reviewedAt);
  assert.equal((edited.versions as unknown[]).length, 1);
  const preview = await tailor(userId, resume.id, job.id, [evidence.id], false);
  assert.ok('previewKey' in preview);
  await assert.rejects(() => tailor(userId, resume.id, job.id, [evidence.id], true, '0'.repeat(64)), /fresh preview/);
  await tailor(userId, resume.id, job.id, [evidence.id], true, 'previewKey' in preview ? preview.previewKey : undefined);
  await assert.rejects(() => tailor(userId, resume.id, job.id, [evidence.id], true, 'previewKey' in preview ? preview.previewKey : undefined), /fresh preview/);
  await assert.rejects(() => createStory(otherId, evidence.id), /not found/);
  await assert.rejects(() => createStory(userId, evidence.id), /allowance/);
  await savePreferences(userId, { roles: ['Engineer'] });
  await savePreferences(userId, { writingStyle: { tone: 'warm', length: 'short' } });
  const prefs = await prisma.careerPreference.findUniqueOrThrow({ where: { userId } });
  assert.deepEqual((prefs.preferences as { roles: string[] }).roles, ['Engineer']);
  await assert.rejects(() => updateEvidence(otherId, evidence.id, { title: 'Forbidden', statement: 'Built React dashboards.', source: 'Fixture', status: 'USER_CONFIRMED', technologies: [], details: {} }), /not found/);
  await updateEvidence(userId, evidence.id, { title: 'Dashboard', statement: 'Built React dashboards.', source: 'Synthetic fixture', status: 'USER_CONFIRMED', technologies: ['React'], details: { situation: 'Repeated dashboard components', result: 'Reusable components delivered' } });
  assert.equal((await prisma.careerDocument.findUniqueOrThrow({ where: { id: draft.id } })).reviewedAt, null);
  assert.equal((await prisma.resume.findUniqueOrThrow({ where: { id: resume.id } })).version, 2);
  const attempts = await Promise.allSettled(Array.from({ length: 6 }, () => createDraft(userId, input)));
  assert.equal(attempts.filter(r => r.status === 'fulfilled').length, 4);
  assert.equal((await prisma.careerUsage.findFirst({ where: { userId, feature: 'draft' } }))?.used, 5);
  await Promise.all([chargeRecommendations(userId, 'synthetic-source', ['a', 'b']), chargeRecommendations(userId, 'synthetic-source', ['a', 'b'])]);
  assert.equal((await prisma.careerUsage.findFirst({ where: { userId, feature: 'recommendations' } }))?.used, 2);
  const proPlan = await prisma.plan.findUnique({ where: { slug: 'pro' } });
  assert.ok(proPlan, 'A Pro plan fixture is required for entitlement regression.');
  await prisma.subscription.create({ data: { userId: otherId, planId: proPlan.id, stripeSubscriptionId: `synthetic-${randomUUID()}`, stripeCustomerId: `synthetic-${randomUUID()}`, currentPeriodStart: new Date(), currentPeriodEnd: new Date(Date.now() + 86400000) } });
  const storyEvidence = await saveEvidence(otherId, { title: 'Confirmed project', statement: 'Built reusable components.', source: 'Synthetic project notes', status: 'USER_CONFIRMED', technologies: [], details: { situation: 'Repeated interface patterns', task: 'Build a library', result: 'Delivered reusable components' } });
  const story = await createStory(otherId, storyEvidence.id);
  assert.equal(story.kind, 'INTERVIEW_STORY');
  assert.match(story.body, /Delivered reusable components/);
  assert.equal(story.sections.length, 4);
  assert.equal((await prisma.careerUsage.findFirst({ where: { userId: otherId, feature: 'interview' } }))?.used, 1);
  const application = await prisma.jobApplication.create({ data: { userId, company: 'Synthetic reminder', role: 'Engineer', status: 'APPLIED', reminderAt: new Date(Date.now() - 60000) } });
  const due = await listApplications(userId, {});
  assert.equal(due.dueReminders.length, 1);
  assert.equal(due.items.find(item => item.id === application.id)?.status, 'FOLLOW_UP_DUE');
  assert.equal((await listApplications(userId, {})).dueReminders.length, 0);
  await assert.rejects(() => updateApplication(otherId, application.id, { nextAction: 'Forbidden' }), /not found/);
  await updateApplication(userId, application.id, { reminderAt: new Date(Date.now() - 1000).toISOString(), nextAction: 'Follow up', contactEmail: 'fixture@example.invalid' });
  assert.equal((await listApplications(userId, {})).dueReminders.length, 1);
  assert.equal(await prisma.applicationEvent.count({ where: { applicationId: application.id, type: 'REMINDER_FIRED' } }), 2);
  await prisma.jobApplication.createMany({ data: [1, 2].map(n => ({ userId, company: `Synthetic pagination ${n}`, role: 'Engineer' })) });
  const pageOne = await listApplications(userId, { limit: 2 });
  assert.ok(pageOne.nextCursor);
  const pageTwo = await listApplications(userId, { limit: 2, cursor: pageOne.nextCursor! });
  assert.equal(new Set([...pageOne.items, ...pageTwo.items].map(item => item.id)).size, 3);
  console.log('PASS: ownership isolation, cached analysis, history, resume versions, concurrent quotas, repeatable reminders, complete pagination, stale-preview rejection, evidence review invalidation, saved style and paid interview stories.');
} finally {
  await prisma.user.deleteMany({ where: { id: { in: users } } });
  await prisma.$disconnect();
  await closeRedis();
}
